# Generated by Django 3.2 on 2021-04-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_gender', models.CharField(max_length=10)),
                ('student_dob', models.CharField(max_length=20)),
                ('student_address', models.CharField(max_length=100)),
                ('student_religion', models.CharField(max_length=20)),
                ('student_father_name', models.CharField(max_length=50)),
                ('student_mother_name', models.CharField(max_length=50)),
                ('session_start_date', models.CharField(max_length=20)),
                ('session_end_date', models.CharField(max_length=20)),
            ],
        ),
    ]
