# Generated by Django 3.2 on 2021-04-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20210411_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentclass',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
