# Generated by Django 3.2 on 2021-04-14 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=50)),
                ('branch_email', models.CharField(max_length=60)),
                ('branch_phone_number', models.CharField(max_length=20)),
                ('branch_address', models.CharField(max_length=100)),
                ('branch_status', models.CharField(max_length=100)),
            ],
        ),
    ]
