# Generated by Django 3.2 on 2021-04-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='related_url',
            field=models.CharField(default='/', max_length=50),
            preserve_default=False,
        ),
    ]
